name: envri-wp8-env
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - flask=2.0.3
  - requests
  - numpy=1.23.2
  - scipy
  - netcdf4
  - pydap
  - pandas
  - xarray
  - plotly>=5.4
  - dash>=2.0,<2.1
  - dash-bootstrap-components=1.2.1
  - jupyter-dash
  - folium
  - ipykernel==5.5.5
  - IPython==7.26.0
  - notebook==6.0.3
  - jupyter-server-proxy
  - pip:
    - icoscp
    - toolz
    - mmappickle
#    - fcntl # activate on linux, needs hack on windows
